### ISSUE TITLE
Support optional parameters

### ISSUE THREAD

**Issue by jonathansnd** [richardvanhook/omniauth-salesforce#2]
There's no way to specify the scope, display or immediate parameters for the returned OAuth Token

**Comment by richardvanhook** [comment]
Just added, please add

gem "omniauth-salesforce", ">=1.0.1"

to your Gemfile and let me know how it goes for you.  Also I built an example app here: https://omniauth-salesforce-example.herokuapp.com/

**Comment by jonathansnd** [comment]
Awesome! Thanks Richard!

The only thing missing is a "Custom" option for setting a Custom "My Domain", this is needed for ORGs that have SSO enabled.

**Comment by richardvanhook** [comment]
Yes, ur right.  Not sure how usable it would be for someone to type that in.
