### ISSUE TITLE
invalid_credentials error

### ISSUE THREAD

**Issue by plukevdh** [richardvanhook/omniauth-salesforce#3]
I keep getting this coming back from salesforce and I'm not really sure where to go to start debugging. What would cause this?

```
Started GET "/auth/failure?message=invalid_credentials" for 127.0.0.1 at 2011-12-12 17:55:36 -0500
```

I have cleaned out my sessions/cookies, logged in/out of SF multiple times to try to resolve but no luck.

**Comment by richardvanhook** [comment]
See line 64 https://github.com/intridea/omniauth-oauth/blob/master/lib/omniauth/strategies/oauth.rb

I'm guessing that's the line raising the error.  Do you mind sharing your source?
